rootProject.name = 'MyJustDial'
include ':app'

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
  repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://api.expo.dev/maven' }

    def nodeModulesDir = new File(rootDir, "../node_modules")

    maven { url("$nodeModulesDir/react-native/android") }
    maven { url("$nodeModulesDir/jsc-android/dist") }
  }
}
